"""updates to models

Revision ID: 07ddeee48db9
Revises: 3e7c41c02b3f
Create Date: 2023-11-27 17:04:47.370007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ddeee48db9'
down_revision = '3e7c41c02b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint('merchants_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('merchants_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'merchants', ['merchant_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'orders', ['customer_id'], ['id'])

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('merchants_ibfk_2', 'merchants', ['product_id'], ['id'])
        batch_op.create_foreign_key('merchants_ibfk_1', 'users', ['merchant_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('customers_ibfk_1', 'users', ['customer_id'], ['id'])

    # ### end Alembic commands ###
