"""updates to models

Revision ID: 30a08a79c6b6
Revises: 4128b176cce8
Create Date: 2023-11-27 19:40:42.123912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a08a79c6b6'
down_revision = '4128b176cce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=8, asdecimal=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
