"""updates to models

Revision ID: 4dd49c100bc6
Revises: f2314d7133d8
Create Date: 2023-11-28 20:27:27.475061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd49c100bc6'
down_revision = 'f2314d7133d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'merchants', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
