"""fixes to product and category relationship

Revision ID: 703ce2679aaa
Revises: 97542767d2f4
Create Date: 2023-12-05 14:32:59.619465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '703ce2679aaa'
down_revision = '97542767d2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint('product_categories_ibfk_1', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('product_categories_ibfk_1', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
