"""updates to models

Revision ID: 7afac34a142f
Revises: f330a27f655a
Create Date: 2023-11-27 17:24:04.593743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afac34a142f'
down_revision = 'f330a27f655a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint('product_images_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_images_ibfk_1', 'product_images', ['product_id'], ['id'])

    # ### end Alembic commands ###
