"""updates to model

Revision ID: 97542767d2f4
Revises: 4dd49c100bc6
Create Date: 2023-11-30 01:05:54.681779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97542767d2f4'
down_revision = '4dd49c100bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint('merchants_ibfk_1', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'merchants', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('merchants_ibfk_1', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
