"""updates to models

Revision ID: f330a27f655a
Revises: 07ddeee48db9
Create Date: 2023-11-27 17:21:05.880946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f330a27f655a'
down_revision = '07ddeee48db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_ibfk_1', type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint('merchants_ibfk_2', type_='foreignkey')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'merchants', ['merchant_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('merchants_ibfk_2', 'merchants', ['merchant_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('customers_ibfk_1', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###
